nodeLinker: node-modules

packageExtensions:
  "raw-loader@4.0.2":
    dependencies:
      loader-utils: "1.4.2"
      schema-utils: "2.7.1"

  "html-webpack-plugin@*":
    dependencies:
      lodash: "*"
